# Generated by Django 5.2.4 on 2026-01-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_available_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cakes', 'Cakes'), ('cookies', 'Cookies'), ('pastries', 'Pastries'), ('bread', 'Bread')], max_length=20),
        ),
    ]
