# Generated by Django 5.2.4 on 2026-01-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cakes', 'Cakes'), ('cookies', 'Cookies'), ('bread', 'Bread')], max_length=20),
        ),
    ]
