# Generated by Django 5.2.4 on 2026-01-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('cakes', 'Cakes'), ('cookies', 'Cookies'), ('bread', 'Bread'), ('bisuits', 'Bisuits'), ('pizza', 'Pizza'), ('puff', 'Puff'), ('doughnut', 'Doughnut'), ('muffin', 'Muffin'), ('somasa', 'Somasa')], max_length=20),
        ),
    ]
